CREATE TABLE IF NOT EXISTS users (
    ip VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chats (
    id INTEGER PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    message TEXT,
    ip VARCHAR(255),
    FOREIGN KEY (ip) REFERENCES users(ip)
);